ARDUINO_DIR ?= /work1/cleger/work/misc/arduino/arduino-1.6.5-r5/
MONITOR_PORT := /dev/ttyUSB0
ARDUINO_LIBS := Servo MM545x Keypad Adafruit_NeoPixel
BOARD_TAG :=atmega328bb
BOARDS_TXT := $(ARDUINO_DIR)/hardware/breadboard/avr/boards.txt

include ../../Arduino-Makefile/Arduino.mk

